create table users
(
    id INT PRIMARY KEY AUTO_INCREMENT=1 UNIQUE,
    full_name VARCHAR(255) NOT NULL,
    1C_APTEKA BOOLEAN DEFAULT FALSE,
    1C_ZKGU BOOLEAN  DEFAULT FALSE,
    1С_BGU_1 BOOLEAN DEFAULT FALSE,
    1с_BGU_2 BOOLEAN DEFAULT FALSE,
    1С_DIETA BOOLEAN DEFAULT FALSE,
    MIS BOOLEAN DEFAULT FALSE,
    TIS BOOLEAN DEFAULT FALSE,
    SED BOOLEAN DEFAULT FALSE,

);
